[TRB-52140]: Introduced new configurations (systemWorkloadDetectors & exclusionDetectors) for Kubeturbo.
turbonomic/t8c-install pull request #44
Opened 2023-11-20 17:12 UTC by amd-ibm

Introduced new configurations (systemWorkloadDetectors & exclusionDetectors) for Kubeturbo.

2023-11-21 13:21 UTC, irfanurrehman approved these changes

2023-11-21 14:43 UTC, irfanurrehman requested changes
https://github.ibm.com/turbonomic/kubeturbo/pull/61#pullrequestreview-14715124

2023-11-22 13:42 UTC, irfanurrehman commented
Tested this, had some issues and needed changes. The fix for the issues is pushed as the last commit on this PR (https://github.com/turbonomic/t8c-install/pull/44/commits/f1a855c53273a2aedd5e81bed2007ce96ba6080f)

Test result:
The kubeturbo config map is create

2023-12-06 14:51 UTC, amd-ibm commented
May reopen in the future

2023-12-06 14:51 UTC, closed without merging